import { mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { AgentType } from "@agent-town/shared";
import { createLogger, shellEscape } from "@agent-town/shared";

const log = createLogger("session-recovery");

/** Subdirectory under the base dir where recovery files are stored. */
export const SESSION_RECOVERY_DIR_NAME = "session-recovery";

/** Default base directory for session recovery state. */
const DEFAULT_BASE_DIR = join(homedir(), ".local", "state", "agent-town");

export interface SessionMetadata {
  sessionId: string;
  agentType: AgentType;
  projectDir: string;
  autonomous: boolean;
  model?: string;
  createdAt: string;
}

interface WrapperScriptOptions {
  muxSessionName: string;
  projectDir: string;
  model?: string;
  autonomous?: boolean;
  /** Override base dir for testing. */
  baseDir?: string;
}

/**
 * Build a bash wrapper script that checks for a session metadata file
 * and resumes the session if found, otherwise starts fresh.
 *
 * The script is designed to be the command that zellij/tmux runs,
 * so on session recovery after reboot it automatically resumes
 * instead of creating a new session.
 */
export function buildWrapperScript(opts: WrapperScriptOptions): string {
  const baseDir = opts.baseDir ?? DEFAULT_BASE_DIR;
  const metadataPath = join(baseDir, SESSION_RECOVERY_DIR_NAME, `${opts.muxSessionName}.json`);

  // Build the extra flags string (shared between resume and fresh paths)
  const extraFlags: string[] = [];
  if (opts.model) {
    extraFlags.push(`--model ${shellEscape(opts.model)}`);
  }
  if (opts.autonomous) {
    extraFlags.push("--dangerously-skip-permissions");
  }
  const flagsSuffix = extraFlags.length > 0 ? ` ${extraFlags.join(" ")}` : "";

  const escapedDir = shellEscape(opts.projectDir);

  return `#!/usr/bin/env bash
set -euo pipefail

# Session recovery wrapper — generated by Agent Town
# Mux session: ${opts.muxSessionName}

SESSION_FILE=${shellEscape(metadataPath)}

cd ${escapedDir}

# Check if we are recovering (session file exists with a sessionId)
if [ -f "$SESSION_FILE" ]; then
  SESSION_ID=$(grep -o '"sessionId":"[^"]*"' "$SESSION_FILE" 2>/dev/null | head -1 | cut -d'"' -f4)
  if [ -n "$SESSION_ID" ]; then
    exec claude --resume "$SESSION_ID"${flagsSuffix}
  fi
fi

# Fresh launch — Claude will create a new session
exec claude${flagsSuffix}
`;
}

/**
 * Write session metadata to disk for recovery.
 * Called during heartbeat when a session is mapped to a multiplexer session.
 */
export function writeSessionMetadata(
  muxSessionName: string,
  metadata: SessionMetadata,
  baseDir: string = DEFAULT_BASE_DIR,
): void {
  const dir = join(baseDir, SESSION_RECOVERY_DIR_NAME);
  try {
    mkdirSync(dir, { recursive: true });
    const filePath = join(dir, `${muxSessionName}.json`);
    const content = JSON.stringify(metadata, null, 2);
    writeFileSync(filePath, content);
  } catch (err) {
    log.warn(
      `failed to write session metadata for mux=${muxSessionName}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Read session metadata from disk.
 * Returns null if the file doesn't exist or is invalid.
 */
export function readSessionMetadata(
  muxSessionName: string,
  baseDir: string = DEFAULT_BASE_DIR,
): SessionMetadata | null {
  const filePath = join(baseDir, SESSION_RECOVERY_DIR_NAME, `${muxSessionName}.json`);
  try {
    const data = readFileSync(filePath, "utf-8");
    const parsed = JSON.parse(data) as Record<string, unknown>;
    if (!parsed.sessionId || typeof parsed.sessionId !== "string") {
      return null;
    }
    return parsed as unknown as SessionMetadata;
  } catch (_err) {
    return null;
  }
}

/**
 * Remove session metadata and wrapper script for a multiplexer session.
 * Called when a session is deleted.
 */
export function cleanupSessionRecoveryFiles(muxSessionName: string, baseDir: string = DEFAULT_BASE_DIR): void {
  const dir = join(baseDir, SESSION_RECOVERY_DIR_NAME);
  const metadataPath = join(dir, `${muxSessionName}.json`);
  const scriptPath = join(dir, `${muxSessionName}.sh`);

  for (const filePath of [metadataPath, scriptPath]) {
    try {
      unlinkSync(filePath);
    } catch (_err) {
      // File may not exist — that's fine
    }
  }
}

/**
 * Find and clean up recovery files for a given session ID.
 * Scans all metadata files to find which mux session name maps to this sessionId.
 */
export function cleanupRecoveryBySessionId(sessionId: string, baseDir: string = DEFAULT_BASE_DIR): void {
  const dir = join(baseDir, SESSION_RECOVERY_DIR_NAME);
  try {
    const files = readdirSync(dir);
    for (const file of files) {
      if (!file.endsWith(".json")) continue;
      const muxName = file.slice(0, -5); // Remove .json
      const metadata = readSessionMetadata(muxName, baseDir);
      if (metadata?.sessionId === sessionId) {
        cleanupSessionRecoveryFiles(muxName, baseDir);
        log.info(`cleaned up recovery files for session=${sessionId} mux=${muxName}`);
        return;
      }
    }
  } catch (_err) {
    // Directory may not exist — that's fine
  }
}

/**
 * Write a wrapper script to disk and make it executable.
 * Returns the path to the script.
 */
export async function writeWrapperScript(
  muxSessionName: string,
  opts: WrapperScriptOptions,
  baseDir: string = DEFAULT_BASE_DIR,
): Promise<string> {
  const dir = join(baseDir, SESSION_RECOVERY_DIR_NAME);
  mkdirSync(dir, { recursive: true });

  const scriptPath = join(dir, `${muxSessionName}.sh`);
  const content = buildWrapperScript(opts);

  await Bun.write(scriptPath, content);

  // Make executable
  const chmod = Bun.spawn(["chmod", "+x", scriptPath], {
    stdout: "ignore",
    stderr: "ignore",
  });
  await chmod.exited;

  log.info(`wrote wrapper script: ${scriptPath}`);
  return scriptPath;
}
